### ISSUE TITLE
Inconsistent: Files Array in CVE Sighting

### ISSUE THREAD

**Issue by dfirence** [mcafee-enterprise/ac3-threat-sightings#15]
Schema `1.6`, `files` array.  Inconsistent 

![067A4C8C-2714-4108-94DA-D1ED381ECA9C](https://user-images.githubusercontent.com/11415591/140596374-7b7bdb76-9592-4549-9f78-83d4a712388f.jpeg)

<br />
<br />

![B441D469-C787-4C8F-A6B0-8942D0BE6EF9](https://user-images.githubusercontent.com/11415591/140596375-1fb01057-0b68-419d-8725-bcbfdc4481d9.jpeg)

**Comment by jstnk9** [comment]
fixed
